server:
  port: 8084
mybatis:
  type-aliases-package: com.redDabbler.review.demo.springboot
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/bill

